version: '3.9'

services:

  git_in_docker:
    image: git_in_docker:latest
    build: .
    volumes:
      - ./ssh:/ssh
      - ./projects:/projects
    command: ["git", "clone", "git@github.com:rajiff/GitInDocker.git"]
    # command: ["git", "--help"]
